/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import subForm.*;

/**
 *
 * @author Afif Bahtiar
 */
public class Buku extends javax.swing.JInternalFrame {
    
    GridBagLayout gb = new GridBagLayout();
    inputBuku ib;
    kelolaBuku kb;

    /**
     * Creates new form Buku
     */
    public Buku(){
        
        try {
            initComponents();
            ib = new inputBuku();
            kb = new kelolaBuku();
            dynamicPanel.setLayout(gb);
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = gbc.gridy = 0;
            dynamicPanel.add(ib, gbc);
            dynamicPanel.add(kb, gbc);
            
            ib.setVisible(true);
            kb.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        formMenu = new javax.swing.JMenu();
        inputMenu = new javax.swing.JMenuItem();
        lihatMenu = new javax.swing.JMenuItem();

        setTitle("Data Buku");
        setPreferredSize(new java.awt.Dimension(1354, 632));

        dynamicPanel.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1331, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        formMenu.setText("Form");
        formMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMenuActionPerformed(evt);
            }
        });

        inputMenu.setText("Input Data");
        inputMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMenuActionPerformed(evt);
            }
        });
        formMenu.add(inputMenu);

        lihatMenu.setText("Lihat Data");
        lihatMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatMenuActionPerformed(evt);
            }
        });
        formMenu.add(lihatMenu);

        jMenuBar1.add(formMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMenuActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formMenuActionPerformed

    private void lihatMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatMenuActionPerformed
        // TODO add your handling code here:
        ib.setVisible(false);
        kb.setVisible(true);
    }//GEN-LAST:event_lihatMenuActionPerformed

    private void inputMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMenuActionPerformed
        // TODO add your handling code here:
        ib.setVisible(true);
        kb.setVisible(false);
    }//GEN-LAST:event_inputMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JMenu formMenu;
    private javax.swing.JMenuItem inputMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem lihatMenu;
    // End of variables declaration//GEN-END:variables
}
