/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import subForm.*;

/**
 *
 * @author Afif Bahtiar
 */
public class Petugas extends javax.swing.JInternalFrame {
    
    GridBagLayout gb = new GridBagLayout();
    kelolaPetugas kp;
    profilPetugas pp;

    /**
     * Creates new form Petugas
     */
    public Petugas(){
        
        try {
            initComponents();
            kp = new kelolaPetugas();
            pp = new profilPetugas();
            dynamicPanel.setLayout(gb);
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = gbc.gridy = 0;
            dynamicPanel.add(kp, gbc);
            dynamicPanel.add(pp, gbc);
            
            kp.setVisible(true);
            pp.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicPanel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        kelPetugasMenu = new javax.swing.JMenuItem();
        profilMenu = new javax.swing.JMenuItem();

        setTitle("Data Petugas");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1354, 632));

        dynamicPanel.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1331, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jMenu2.setText("Form");

        kelPetugasMenu.setText("Kelola Petugas");
        kelPetugasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelPetugasMenuActionPerformed(evt);
            }
        });
        jMenu2.add(kelPetugasMenu);

        profilMenu.setText("Profil Saya");
        profilMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilMenuActionPerformed(evt);
            }
        });
        jMenu2.add(profilMenu);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelPetugasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelPetugasMenuActionPerformed
        // TODO add your handling code here:
        kp.setVisible(true);
        pp.setVisible(false);
        
    }//GEN-LAST:event_kelPetugasMenuActionPerformed

    private void profilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilMenuActionPerformed
        // TODO add your handling code here:
        pp.setVisible(true);
        kp.setVisible(false);
        
    }//GEN-LAST:event_profilMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem kelPetugasMenu;
    private javax.swing.JMenuItem profilMenu;
    // End of variables declaration//GEN-END:variables
}
