/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplemenu;

import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import form.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import connector.MySqlCon;
import data.Data;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Afif Bahtiar
 */
public class SimpleMenuSwitch extends javax.swing.JFrame {

    /**
     * Creates new form SimpleMenuSwitch
     */
    Data data = new Data();

    public SimpleMenuSwitch() {
        initComponents();
        this.setExtendedState(SimpleMenuSwitch.MAXIMIZED_BOTH);
        peminjamanBtn.setEnabled(false);
        pengembalianBtn.setEnabled(false);
        peminjamBtn.setEnabled(false);
        petugasBtn.setEnabled(false);
        dataBukuBtn.setEnabled(false);
        kategoriBukuBtn.setEnabled(false);
        aboutBtn.setEnabled(false);
        logoutbtn.setEnabled(false);

    }

    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = SimpleMenuSwitch.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(false);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }

    public void clear() {

        dPanel.removeAll();
        dPanel.repaint();
        dPanel.add(panel);
        tfuser.setText("");
        tfpass.setText("");
        peminjamanBtn.setEnabled(false);
        pengembalianBtn.setEnabled(false);
        peminjamBtn.setEnabled(false);
        petugasBtn.setEnabled(false);
        dataBukuBtn.setEnabled(false);
        kategoriBukuBtn.setEnabled(false);
        aboutBtn.setEnabled(false);
        logoutbtn.setEnabled(false);
        Data.setNamaPetugas("");
        Data.setUserId("");
    }

    public void cek() {

        String sql = "SELECT * FROM petugas where username = '" + tfuser.getText() + "' and passwd = '" + tfpass.getText() + "'";

        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                if (rs.getString("level").equals("Ketua")) {
                    peminjamanBtn.setEnabled(true);
                    pengembalianBtn.setEnabled(true);
                    peminjamBtn.setEnabled(true);
                    petugasBtn.setEnabled(true);
                    dataBukuBtn.setEnabled(true);
                    kategoriBukuBtn.setEnabled(true);
                    aboutBtn.setEnabled(true);
                    logoutbtn.setEnabled(true);
                    dataBukuBtn.doClick();

                    // this.dispose();
                } else if (rs.getString("level").equals("Petugas")) {

                    peminjamanBtn.setEnabled(true);
                    pengembalianBtn.setEnabled(true);
                    peminjamBtn.setEnabled(true);
                    petugasBtn.setEnabled(true);
                    dataBukuBtn.setEnabled(true);
                    kategoriBukuBtn.setEnabled(true);
                    aboutBtn.setEnabled(true);
                    logoutbtn.setEnabled(true);
                    dataBukuBtn.doClick();
                }
                Data.setNamaPetugas(rs.getString("nama_petugas"));
                Data.setUserId(rs.getString("id_petugas"));
            } else {
                JOptionPane.showMessageDialog(null, "Maaf password atau username anda salah");
                tfuser.setText("");
                tfpass.setText("");
                tfuser.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peminjamanBtn = new javax.swing.JButton();
        dPanel = new javax.swing.JDesktopPane();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        tfpass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pengembalianBtn = new javax.swing.JButton();
        peminjamBtn = new javax.swing.JButton();
        petugasBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        dataBukuBtn = new javax.swing.JButton();
        kategoriBukuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        peminjamanBtn.setText("Data Peminjaman");
        peminjamanBtn.setPreferredSize(new java.awt.Dimension(140, 32));
        peminjamanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanBtnActionPerformed(evt);
            }
        });

        dPanel.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setText("Username :");

        jLabel4.setText("Password :");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(91, 91, 91)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfuser)
                                    .addComponent(tfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login)
                .addGap(32, 32, 32))
        );

        dPanel.setLayer(panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        pengembalianBtn.setText("Data Pengembalian");
        pengembalianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianBtnActionPerformed(evt);
            }
        });

        peminjamBtn.setText("Data Peminjam");
        peminjamBtn.setPreferredSize(new java.awt.Dimension(140, 32));
        peminjamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamBtnActionPerformed(evt);
            }
        });

        petugasBtn.setText("Data Petugas");
        petugasBtn.setPreferredSize(new java.awt.Dimension(140, 32));
        petugasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasBtnActionPerformed(evt);
            }
        });

        aboutBtn.setText("About");
        aboutBtn.setPreferredSize(new java.awt.Dimension(140, 32));

        logoutbtn.setText("Log Out");
        logoutbtn.setPreferredSize(new java.awt.Dimension(140, 32));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        dataBukuBtn.setText("Data Buku");
        dataBukuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBukuBtnActionPerformed(evt);
            }
        });

        kategoriBukuBtn.setText("Data Kategori Buku");
        kategoriBukuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriBukuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dPanel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(peminjamanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengembalianBtn)
                .addGap(18, 18, 18)
                .addComponent(peminjamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(petugasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataBukuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kategoriBukuBtn)
                .addGap(18, 18, 18)
                .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategoriBukuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pengembalianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(peminjamanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(peminjamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataBukuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(petugasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peminjamanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanBtnActionPerformed
        // TODO add your handling code here:
        dPanel.removeAll();
        dPanel.repaint();
        Peminjaman p = new Peminjaman();

        dPanel.add(p);
        p.setVisible(true);
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_peminjamanBtnActionPerformed

    private void pengembalianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianBtnActionPerformed
        // TODO add your handling code here:
        dPanel.removeAll();
        dPanel.repaint();
        Pengembalian p = new Pengembalian();

        dPanel.add(p);
        p.setVisible(true);
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pengembalianBtnActionPerformed

    private void peminjamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamBtnActionPerformed
        try {
            // TODO add your handling code here:
            dPanel.removeAll();
            dPanel.repaint();
            Peminjam p = new Peminjam();

            dPanel.add(p);
            p.setVisible(true);
            try {
                p.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_peminjamBtnActionPerformed

    private void dataBukuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBukuBtnActionPerformed
        // TODO add your handling code here:
        try {
            dPanel.removeAll();
            dPanel.repaint();
            Buku b = new Buku();

            dPanel.add(b);
            b.setVisible(true);
            try {
                b.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataBukuBtnActionPerformed

    private void kategoriBukuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriBukuBtnActionPerformed
        // TODO add your handling code here:
        try {
            dPanel.removeAll();
            dPanel.repaint();
            Kategori k = new Kategori();

            dPanel.add(k);
            k.setVisible(true);
            try {
                k.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kategoriBukuBtnActionPerformed

    private void petugasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasBtnActionPerformed
        // TODO add your handling code here:
        try {
            dPanel.removeAll();
            dPanel.repaint();
            String levelPetugas = "";
            Petugas p = new Petugas();
            Petugas1 p1 = new Petugas1();

            String sql = "select level from petugas where id_petugas = '" + Data.getUserId() + "'";
            try {
                Statement st = MySqlCon.getConnection().createStatement();
                ResultSet rs = st.executeQuery(sql);

                if (rs.next()) {
                    levelPetugas = rs.getString("level");

                } else {
                    JOptionPane.showMessageDialog(this, "Terdapat kesalahan dalam query!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Query salah " + e);
            }

            if (levelPetugas.equals("Ketua")) {
                dPanel.add(p);
                p.setVisible(true);
                try {
                    p.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                dPanel.add(p1);
                p1.setVisible(true);
                try {
                    p1.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(SimpleMenuSwitch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_petugasBtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        cek();
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleMenuSwitch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    public javax.swing.JDesktopPane dPanel;
    private javax.swing.JButton dataBukuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kategoriBukuBtn;
    private javax.swing.JButton login;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel panel;
    private javax.swing.JButton peminjamBtn;
    private javax.swing.JButton peminjamanBtn;
    private javax.swing.JButton pengembalianBtn;
    private javax.swing.JButton petugasBtn;
    private javax.swing.JPasswordField tfpass;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
}
