/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subForm;

import connector.MySqlCon;
import data.Data;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Afif Bahtiar
 */
public class inputPeminjaman extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form inputPeminjaman
     */
    static String novel = "novel";
    static String paket = "paket";

    String limit = "";
    String pengembalian = "";

    private String[] listBuku = new String[20];
    private int index = 0;

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
    String Tanggal = tgl.format(cal.getTime());

    Calendar calendar = Calendar.getInstance();
    SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");
    String today = tanggal.format(calendar.getTime());

    private String kodePinjam = "";

    public inputPeminjaman() {
        initComponents();
        radioGroup.add(novelRadioBtn);
        radioGroup.add(paketRadioBtn);
        novelRadioBtn.setActionCommand(novel);
        paketRadioBtn.setActionCommand(paket);

        novelRadioBtn.addActionListener(this);
        paketRadioBtn.addActionListener(this);
        novelRadioBtn.setSelected(true);
        kodePinjam = "nvl";
        todayDate.setText(Tanggal);

        loginInfoLbl.setText(Data.namaPetugas + " - " + Data.userId);
        pengembalianDate.setText(getPengembalianDate(todayDate.getText(), 2));
        limitDate.setText(getPengembalianDate(todayDate.getText(), 3));
        pengembalian = formatPengembalianDate(today, 2);
        limit = formatPengembalianDate(today, 3);

    }

    private String getPengembalianDate(String date, int day) {

        String pengembalianDate = "";
        try {

            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
            Calendar todayDate = Calendar.getInstance();
            todayDate.setTime(format.parse(date));
            todayDate.add(Calendar.DATE, day);
            pengembalianDate = format.format(todayDate.getTime());

        } catch (ParseException ex) {
            Logger.getLogger(inputPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }

        return pengembalianDate;
    }

    private String formatPengembalianDate(String date, int day) {

        String pengembalianDate = "";
        try {

            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Calendar todayDate = Calendar.getInstance();
            todayDate.setTime(format.parse(date));
            todayDate.add(Calendar.DATE, day);
            pengembalianDate = format.format(todayDate.getTime());

        } catch (ParseException ex) {
            Logger.getLogger(inputPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }

        return pengembalianDate;
    }

    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals(paket)) {
            pengembalianDate.setText(getPengembalianDate(todayDate.getText(), 183));
            limitDate.setText(getPengembalianDate(todayDate.getText(), 184));
            pengembalian = formatPengembalianDate(today, 183);
            limit = formatPengembalianDate(today, 184);
            kodePinjam = "pkt";
        } else if (e.getActionCommand().equals(novel)) {
            pengembalianDate.setText(getPengembalianDate(todayDate.getText(), 2));
            limitDate.setText(getPengembalianDate(todayDate.getText(), 3));
            pengembalian = formatPengembalianDate(today, 2);
            limit = formatPengembalianDate(today, 3);
            kodePinjam = "nvl";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        todayDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noIndukTf = new javax.swing.JTextField();
        inputBookBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTa = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pengembalianDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        limitDate = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        novelRadioBtn = new javax.swing.JRadioButton();
        paketRadioBtn = new javax.swing.JRadioButton();
        loginInfoLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        bukuTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cekIdBtn = new javax.swing.JButton();
        namaSiswaLbl = new javax.swing.JLabel();

        setName("Input Peminjaman"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1311, 559));

        jLabel1.setText("Server Date :");

        todayDate.setText("Today_date");

        jLabel3.setText("No Induk Peminjam          :");

        inputBookBtn.setText("Input Buku");
        inputBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBookBtnActionPerformed(evt);
            }
        });

        listTa.setColumns(20);
        listTa.setRows(5);
        jScrollPane1.setViewportView(listTa);
        listTa.setEditable(false);

        jLabel4.setText("Daftar buku yang dipinjam siswa");

        jLabel5.setText("Tanggal Pengembalian   :");

        pengembalianDate.setText("Today_date+2");

        jLabel7.setText("Batas Pengembalian       :");

        limitDate.setText("Tanggal_pengembalian+1");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        novelRadioBtn.setText("Novel / Cerpen");

        paketRadioBtn.setText("LKS / Paket");

        loginInfoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginInfoLbl.setText("Nama Petugasnya disini!!");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Id buku yang dipinjam      :");

        cekIdBtn.setText("Cek");
        cekIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekIdBtnActionPerformed(evt);
            }
        });

        namaSiswaLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaSiswaLbl.setText("Nama Siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(todayDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pengembalianDate))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(limitDate)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(novelRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paketRadioBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bukuTf, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(noIndukTf))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(inputBookBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cekIdBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(namaSiswaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(loginInfoLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(715, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(todayDate)
                    .addComponent(loginInfoLbl))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(noIndukTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekIdBtn)
                    .addComponent(namaSiswaLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBookBtn)
                    .addComponent(clearBtn)
                    .addComponent(bukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novelRadioBtn)
                    .addComponent(paketRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pengembalianDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(limitDate))
                .addGap(29, 29, 29)
                .addComponent(submitBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        submitBtn.setEnabled(false);
    }// </editor-fold>//GEN-END:initComponents

    private void inputBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBookBtnActionPerformed

        String sql = "select * from data_buku where kode_buku = '" + bukuTf.getText() + "'";

        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                if (rs.getString("keterangan").equals("Tersedia")) {

                    String namaBuku = rs.getString("nama_buku");
                    listTa.append(bukuTf.getText() + " - " + namaBuku + "\n");
                    listBuku[index] = bukuTf.getText();
                    index++;
                    bukuTf.setText("");

                } else if (rs.getString("keterangan").equals("Dipinjam")) {
                    JOptionPane.showMessageDialog(this, "Buku telah dipinjam!");
                    bukuTf.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(this, "kode buku salah!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah " + e);
        }
    }//GEN-LAST:event_inputBookBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        listTa.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cekIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekIdBtnActionPerformed
        // TODO add your handling code here:
        String sql = "select * from peminjam where no_induk='" + noIndukTf.getText() + "'";

        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                namaSiswaLbl.setText(rs.getString("nama_siswa"));
                submitBtn.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Nomor induk yang anda inputkan salah!");
                submitBtn.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah " + e);
        }
    }//GEN-LAST:event_cekIdBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String date = todayDate.getText();
        String replace = date.replace("-", "");
        String idTrans = noIndukTf.getText() + "-" + replace + "-" + Data.getUserId() + "-" + kodePinjam;
        JOptionPane.showMessageDialog(this, idTrans);

        String sql = "insert into transaksi_pinjam values('" + idTrans + "','" + noIndukTf.getText() + "','" + Data.getUserId() + "','" + today + "','" + pengembalian + "','" + limit + "')";
        try {
            MySqlCon.ExecuteQuery(sql, "Data peminjaman berhasil dimasukkan");
            noIndukTf.setText("");
            listTa.setText("");
        } catch (Exception ex) {
            Logger.getLogger(inputPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }

        String nextSql;
        for (int i = 0; i < index; i++) {
            nextSql = "insert into melibatkan values('" + idTrans + "','" + listBuku[i] + "')";
            try {
                MySqlCon.ExecuteQuery(nextSql, "Data buku yang dipinjam berhasil dimasukkan");
            } catch (Exception ex) {
                Logger.getLogger(inputPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        String updateSql;
        for (int i = 0; i < index; i++) {
            updateSql = "update data_buku set keterangan= 'Dipinjam' where kode_buku = '"+listBuku[i]+"'";
            try {
                MySqlCon.ExecuteQuery(updateSql, "Data buku telah diubah");
            } catch (Exception ex) {
                Logger.getLogger(inputPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        index = 0;
        listBuku = new String[30];
        submitBtn.setEnabled(false);
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bukuTf;
    private javax.swing.JButton cekIdBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton inputBookBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limitDate;
    private javax.swing.JTextArea listTa;
    private javax.swing.JLabel loginInfoLbl;
    private javax.swing.JLabel namaSiswaLbl;
    private javax.swing.JTextField noIndukTf;
    private javax.swing.JRadioButton novelRadioBtn;
    private javax.swing.JRadioButton paketRadioBtn;
    private javax.swing.JLabel pengembalianDate;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel todayDate;
    // End of variables declaration//GEN-END:variables
}
