/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subForm;

import connector.MySqlCon;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Afif Bahtiar
 */
public class inputBuku extends javax.swing.JPanel {

    /**
     * Creates new form inputPeminjaman
     */
    
    private String kodeKategori="";
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
    String Tanggal = tgl.format(cal.getTime());
    
    public inputBuku() {
        initComponents();
        getKategoriList();
        todayDate.setText(Tanggal);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        todayDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeBukuTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        insertBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kelasCb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jumHalamanTf = new javax.swing.JTextField();
        tahunTerbitTf = new javax.swing.JTextField();
        penerbitTf = new javax.swing.JTextField();
        kotaTf = new javax.swing.JTextField();
        namaBukuTf = new javax.swing.JTextField();
        kategoriCb = new javax.swing.JComboBox<>();
        clearBtn = new javax.swing.JButton();

        setName("Input Peminjaman"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1311, 559));

        jLabel1.setText("Server Date :");

        todayDate.setText("Today_date");

        jLabel3.setText("Kode buku                          :");

        jLabel5.setText("Nama kategori                  :");

        jLabel7.setText("Nama Buku                        :");

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Penerbit                              :");

        jLabel6.setText("Kota                                     :");

        jLabel8.setText("Tahun terbit                       :");

        kelasCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII", "Bebas" }));

        jLabel10.setText("Jumlah halaman              :");

        jLabel11.setText("Kelas                                   :");

        jumHalamanTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumHalamanTfActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(todayDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tahunTerbitTf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(penerbitTf, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kategoriCb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jumHalamanTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kelasCb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(50, 50, 50)
                                                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(kodeBukuTf))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kotaTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaBukuTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(737, 737, 737))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(todayDate))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kodeBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kategoriCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(penerbitTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kotaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tahunTerbitTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jumHalamanTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kelasCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(clearBtn))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
            // TODO add your handling code here:
            String kode = getKodeKategori(kategoriCb.getSelectedItem().toString());
            String query = "INSERT INTO data_buku VALUES('"+kodeBukuTf.getText()+"', '"+kode+"', '"+namaBukuTf.getText()+"', '"+penerbitTf.getText()+"', '"+kotaTf.getText()+"', '"+tahunTerbitTf.getText()+"', '"+jumHalamanTf.getText()+"', '"+kelasCb.getSelectedItem()+"', 'Tersedia')";
        try {
            MySqlCon.ExecuteQuery(query,"Data buku berhasil dimasukkan");
            kodeBukuTf.setText("");
            namaBukuTf.setText("");
            penerbitTf.setText("");
            kotaTf.setText("");
            tahunTerbitTf.setText("");
            jumHalamanTf.setText("");
        } catch (Exception ex) {
            Logger.getLogger(inputBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_insertBtnActionPerformed

    private void getKategoriList(){
        String query = "select * from data_kategori_buku";
        try{
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                kategoriCb.addItem(rs.getString("nama_kategori"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : "+e);
        }
    }
    
    private String getKodeKategori(String namaKategori){
        String query = "select * from data_kategori_buku where nama_kategori = '"+namaKategori+"'";
        try{
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                kodeKategori = rs.getString("id_kategori");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : "+e);
        }
        
        return kodeKategori;
    }
    
    private void jumHalamanTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumHalamanTfActionPerformed
    }//GEN-LAST:event_jumHalamanTfActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        kodeBukuTf.setText("");
        namaBukuTf.setText("");
        penerbitTf.setText("");
        kotaTf.setText("");
        tahunTerbitTf.setText("");
        jumHalamanTf.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jumHalamanTf;
    private javax.swing.JComboBox<String> kategoriCb;
    private javax.swing.JComboBox<String> kelasCb;
    private javax.swing.JTextField kodeBukuTf;
    private javax.swing.JTextField kotaTf;
    private javax.swing.JTextField namaBukuTf;
    private javax.swing.JTextField penerbitTf;
    private javax.swing.JTextField tahunTerbitTf;
    private javax.swing.JLabel todayDate;
    // End of variables declaration//GEN-END:variables
}
