/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subForm;

import connector.MySqlCon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Afif Bahtiar
 */
public class kelolaBuku extends javax.swing.JPanel {

    /**
     * Creates new form kelolaPeminjaman
     */
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
    String Tanggal = tgl.format(cal.getTime());
    private String kodeKategori = "", namaKategori = "", flag = "";

    public kelolaBuku() throws Exception {
        initComponents();
        showTbBuku("select * from data_buku");
        getKategoriList();
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateDataPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_kodeBuku = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kelasCb = new javax.swing.JComboBox<>();
        jumhalamanTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaBukuTf = new javax.swing.JTextField();
        kategoriCb = new javax.swing.JComboBox<>();
        penerbitTf = new javax.swing.JTextField();
        kotaTf = new javax.swing.JTextField();
        tahunTerbitTf = new javax.swing.JTextField();
        keteranganCb = new javax.swing.JComboBox<>();
        cancelBtn = new javax.swing.JButton();
        SortPane = new javax.swing.JPanel();
        btnShowAll = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        isiCb = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();
        proceedBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1311, 559));

        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBuku);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari data pencarian berdasarkan kodenya!!");

        updateDataPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateDataPanel.setForeground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Form Ubah Data");

        jLabel5.setText("Kode Buku    :");

        lbl_kodeBuku.setText("-");

        jLabel7.setText("Id Kategori    :");

        jLabel8.setText("Nama Buku   :");

        jLabel9.setText("Penerbit         :");

        jLabel10.setText("Kota                :");

        kelasCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII", "Bebas" }));

        jLabel11.setText("Tahun Terbit                :");

        jLabel12.setText("Jumlah halaman        :");

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Kelas                             :");

        jLabel6.setText("Keterangan                  :");

        keteranganCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Dipinjam" }));

        cancelBtn.setText("Cancel");
        cancelBtn.setEnabled(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateDataPanelLayout = new javax.swing.GroupLayout(updateDataPanel);
        updateDataPanel.setLayout(updateDataPanelLayout);
        updateDataPanelLayout.setHorizontalGroup(
            updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kotaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(penerbitTf)
                    .addComponent(namaBukuTf)
                    .addComponent(lbl_kodeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kategoriCb, 0, 238, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tahunTerbitTf)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kelasCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumhalamanTf)
                            .addComponent(keteranganCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 57, 57))
            .addGroup(updateDataPanelLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateDataPanelLayout.setVerticalGroup(
            updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDataPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tahunTerbitTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumhalamanTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelasCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(keteranganCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_kodeBuku))
                        .addGap(9, 9, 9)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(kategoriCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(namaBukuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(penerbitTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kotaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SortPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SortPaneLayout = new javax.swing.GroupLayout(SortPane);
        SortPane.setLayout(SortPaneLayout);
        SortPaneLayout.setHorizontalGroup(
            SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortPaneLayout.createSequentialGroup()
                .addContainerGap(1210, Short.MAX_VALUE)
                .addComponent(btnShowAll)
                .addContainerGap())
        );
        SortPaneLayout.setVerticalGroup(
            SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortPaneLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnShowAll)
                .addGap(6, 6, 6))
        );

        jLabel13.setText("Tampilkan tabel menurut kolomnya");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Kelas", "Keterangan" }));

        btnGo.setText("Go!");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(proceedBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isiCb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGo))))
                        .addGap(94, 94, 94)
                        .addComponent(updateDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SortPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proceedBtn))
                    .addComponent(updateDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SortPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        isiCb.setEnabled(false);
        proceedBtn.setEnabled(false);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfCari.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap isi kolom pencarian!!");
        } else {
            showTbBuku("select * from data_buku where kode_buku = '" + tfCari.getText() + "'");
            tfCari.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        showTbBuku("select * from data_buku");
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void tabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBukuMouseClicked
        // TODO add your handling code here:
        try {
            Statement st = MySqlCon.getConnection().createStatement();
            int baris = tabelBuku.getSelectedRow();
            String klik_tabel = (tabelBuku.getModel().getValueAt(baris, 0).toString());
            String query = "select * from data_buku where kode_buku = '" + klik_tabel + "'";
            String kode = "", id = "", nama = "", penerbit = "", kota = "", tahun = "", halaman = "", kelas = "", keterangan = "";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                kode = rs.getString("kode_buku");
                id = rs.getString("id_kategori");
                nama = rs.getString("nama_buku");
                kelas = rs.getString("kelas");
                penerbit = rs.getString("penerbit");
                tahun = rs.getString("tahun_terbit");
                kota = rs.getString("kota");
                halaman = rs.getString("jum_halaman");
                keterangan = rs.getString("keterangan");
                lbl_kodeBuku.setText(kode);
                kategoriCb.setSelectedItem(getNamaKategori(id));
                namaBukuTf.setText(nama);
                kelasCb.setSelectedItem(kelas);
                penerbitTf.setText(penerbit);
                tahunTerbitTf.setText(tahun);
                kotaTf.setText(kota);
                jumhalamanTf.setText(halaman);
                keteranganCb.setSelectedItem(keterangan);
                updateBtn.setEnabled(true);
                cancelBtn.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah");
        }
    }//GEN-LAST:event_tabelBukuMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            // TODO add your handling code here:
            String namaKategori = getKodeKategori(kategoriCb.getSelectedItem().toString());
            String query = "update data_buku set id_kategori='" + namaKategori + "',nama_buku ='" + namaBukuTf.getText() + "', "
                    + "penerbit='" + penerbitTf.getText() + "', kota='" + kotaTf.getText() + "',tahun_terbit='" + tahunTerbitTf.getText() + "',jum_halaman='" + jumhalamanTf.getText() + "', "
                    + "kelas='" + kelasCb.getSelectedItem() + "', keterangan='" + keteranganCb.getSelectedItem() + "' where kode_buku='" + lbl_kodeBuku.getText() + "'";
            PreparedStatement ps = MySqlCon.getConnection().prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            showTbBuku("select * from data_buku");
            ps.close();
            lbl_kodeBuku.setText("-");
            namaBukuTf.setText("");
            kelasCb.setSelectedItem("");
            penerbitTf.setText("");
            tahunTerbitTf.setText("");
            kotaTf.setText("");
            jumhalamanTf.setText("");
            updateBtn.setEnabled(false);
            cancelBtn.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Query salah \nError : " + ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        lbl_kodeBuku.setText("-");
        namaBukuTf.setText("");
        kelasCb.setSelectedItem("");
        penerbitTf.setText("");
        tahunTerbitTf.setText("");
        kotaTf.setText("");
        jumhalamanTf.setText("");
        updateBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        String[] kelItem = {"X", "XI", "XII", "Bebas"};
        String[] ketItem = {"Tersedia", "Dipinjam"};
        switch (cbKategori.getSelectedItem().toString()) {
            case "Kelas":

                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                for (String itemKel : kelItem) {
                    isiCb.addItem(itemKel);
                }
                flag = "kelas";
                break;
            case "Kategori":
                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                getKategoriList();
                flag = "id_kategori";
                break;
            case "Keterangan":
                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                for (String itemKet : ketItem) {
                    isiCb.addItem(itemKet);
                }
                flag = "keterangan";
                break;
            default:
                JOptionPane.showInputDialog(this, "Input salah");
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        if(flag.equals("id_kategori")){
            String kode = getKodeKategori((String) isiCb.getSelectedItem());
            showTbBuku("select * from data_buku where " + flag + " = '" + kode + "'");
        }else{
            showTbBuku("select * from data_buku where " + flag + " = '" + isiCb.getSelectedItem() + "'");
        }
        
        isiCb.setEnabled(false);
        proceedBtn.setEnabled(false);
        flag = "";
        isiCb.removeAllItems();

    }//GEN-LAST:event_proceedBtnActionPerformed

    private void getKategoriList() {
        String query = "select * from data_kategori_buku";
        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                kategoriCb.addItem(rs.getString("nama_kategori"));
                isiCb.addItem(rs.getString("nama_kategori"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : " + e);
        }
    }

    private String getKodeKategori(String namaKategori) {
        String query = "select * from data_kategori_buku where nama_kategori = '" + namaKategori + "'";
        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                kodeKategori = rs.getString("id_kategori");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : " + e);
        }

        return kodeKategori;
    }

    private String getNamaKategori(String idKategori) {
        String query = "select * from data_kategori_buku where id_kategori = '" + idKategori + "'";
        try {
            Statement st = MySqlCon.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                namaKategori = rs.getString("nama_kategori");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Query salah \nError kode : " + e);
        }

        return namaKategori;
    }

    private void showTbBuku(String query) {
        try {
            Statement st = MySqlCon.getConnection().createStatement();
            try {
                Object[] rows = {"Kode buku", "Id kategori", "Nama buku", "Penerbit", "Kota", "Tahun terbit", "Jumlah halaman", "Kelas", "Keterangan"};
                DefaultTableModel dtm = new DefaultTableModel(null, rows);
                tabelBuku.setModel(dtm);
                tabelBuku.setBorder(null);
                jScrollPane1.setVisible(true);
                jScrollPane1.setViewportView(tabelBuku);
                String kode = "", id = "", nama = "", penerbit = "", kota = "", tahun = "", halaman = "", kelas = "", keterangan = "";
                try {

                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        kode = rs.getString("kode_buku");
                        id = rs.getString("id_kategori");
                        nama = rs.getString("nama_buku");
                        kelas = rs.getString("kelas");
                        penerbit = rs.getString("penerbit");
                        tahun = rs.getString("tahun_terbit");
                        kota = rs.getString("kota");
                        halaman = rs.getString("jum_halaman");
                        keterangan = rs.getString("keterangan");

                        String[] row = {"" + kode, id, nama, penerbit, kota, tahun, halaman, kelas, keterangan};
                        dtm.addRow(row);
                    }

                } catch (SQLException en) {
                    JOptionPane.showMessageDialog(null, "Query Salah " + en);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Query Salah " + e);
            }
        } catch (Exception ex) {
            Logger.getLogger(kelolaBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SortPane;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> isiCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumhalamanTf;
    private javax.swing.JComboBox<String> kategoriCb;
    private javax.swing.JComboBox<String> kelasCb;
    private javax.swing.JComboBox<String> keteranganCb;
    private javax.swing.JTextField kotaTf;
    private javax.swing.JLabel lbl_kodeBuku;
    private javax.swing.JTextField namaBukuTf;
    private javax.swing.JTextField penerbitTf;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JTable tabelBuku;
    private javax.swing.JTextField tahunTerbitTf;
    private javax.swing.JTextField tfCari;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updateDataPanel;
    // End of variables declaration//GEN-END:variables
}
