/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subForm;

import connector.MySqlCon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Afif Bahtiar
 */
public class kelolaPeminjam extends javax.swing.JPanel {

    /**
     * Creates new form kelolaPeminjaman
     */
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
    String Tanggal = tgl.format(cal.getTime());
    private String flag = "";
    public kelolaPeminjam() throws Exception {
        initComponents();
        showTbPeminjam("select * from peminjam");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjam = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        isiCb = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();
        proceedBtn = new javax.swing.JButton();
        updateDataPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_noInduk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kelasCb = new javax.swing.JComboBox<>();
        jurusanCb = new javax.swing.JComboBox<>();
        jekelCb = new javax.swing.JComboBox<>();
        tfTelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        SortPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        indukBtn = new javax.swing.JButton();
        kelasBtn = new javax.swing.JButton();
        jurusanBtn = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1311, 559));

        tabelPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPeminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjam);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari data pencarian berdasarkan indexnya!!");

        jLabel3.setText("Tampilkan tabel menurut kolomnya");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas", "Jurusan", "Jenis Kelamin" }));

        isiCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII" }));

        btnGo.setText("Go!");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        updateDataPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateDataPanel.setForeground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Form Ubah Data");

        jLabel5.setText("No Induk         :");

        jLabel7.setText("Nama Siswa :");

        jLabel8.setText("Jurusan         :");

        jLabel9.setText("Kelas              :");

        jLabel10.setText("Jenis Kelamin             :");

        kelasCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII" }));

        jurusanCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TPM", "TKR", "TMM", "TEI", "TAV", "TPL", "TSM", "TBO" }));

        jekelCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));

        jLabel11.setText("Alamat                          :");

        alamatTa.setColumns(20);
        alamatTa.setRows(5);
        jScrollPane2.setViewportView(alamatTa);

        jLabel12.setText("Telp                               :");

        jLabel13.setText("+62");

        updateBtn.setText("Ubah");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateDataPanelLayout = new javax.swing.GroupLayout(updateDataPanel);
        updateDataPanel.setLayout(updateDataPanelLayout);
        updateDataPanelLayout.setHorizontalGroup(
            updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createSequentialGroup()
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(updateDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(kelasCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jurusanCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(updateDataPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(updateDataPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_noInduk))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jekelCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDataPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(updateDataPanelLayout.createSequentialGroup()
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel4))
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateDataPanelLayout.setVerticalGroup(
            updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDataPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jekelCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateDataPanelLayout.createSequentialGroup()
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_noInduk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateDataPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel9))
                            .addGroup(updateDataPanelLayout.createSequentialGroup()
                                .addGroup(updateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jurusanCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelasCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SortPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Urutkan data berdasarkan kolom yang anda inginkan!!");

        indukBtn.setText("No Induk");
        indukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indukBtnActionPerformed(evt);
            }
        });

        kelasBtn.setText("Kelas");
        kelasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasBtnActionPerformed(evt);
            }
        });

        jurusanBtn.setText("Jurusan");
        jurusanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanBtnActionPerformed(evt);
            }
        });

        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SortPaneLayout = new javax.swing.GroupLayout(SortPane);
        SortPane.setLayout(SortPaneLayout);
        SortPaneLayout.setHorizontalGroup(
            SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SortPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SortPaneLayout.createSequentialGroup()
                        .addComponent(indukBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(kelasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jurusanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowAll)))
                .addContainerGap())
        );
        SortPaneLayout.setVerticalGroup(
            SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SortPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jurusanBtn)
                        .addComponent(btnShowAll))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SortPaneLayout.createSequentialGroup()
                        .addGroup(SortPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(indukBtn)
                            .addComponent(kelasBtn))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(proceedBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isiCb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGo))))
                        .addGap(94, 94, 94)
                        .addComponent(updateDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SortPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proceedBtn))
                    .addComponent(updateDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SortPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        isiCb.setEnabled(false);
        proceedBtn.setEnabled(false);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tfCari.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap isi kolom pencarian!!");
        }else{
            showTbPeminjam("select * from peminjam where no_induk = '"+tfCari.getText()+"'");
            tfCari.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        showTbPeminjam("select * from peminjam");
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void indukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indukBtnActionPerformed
        // TODO add your handling code here:
        showTbPeminjam("select * from peminjam group by no_induk");
    }//GEN-LAST:event_indukBtnActionPerformed

    private void kelasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasBtnActionPerformed
        // TODO add your handling code here:
        showTbPeminjam("select * from peminjam group by kelas");
    }//GEN-LAST:event_kelasBtnActionPerformed

    private void jurusanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanBtnActionPerformed
        // TODO add your handling code here:
        showTbPeminjam("select * from peminjam group by jurusan");
    }//GEN-LAST:event_jurusanBtnActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        String[] kelItem = {"X","XI","XII"};
        String[] jurItem = {"TPM", "TKR", "TMM", "TEI", "TAV", "TPL", "TSM", "TBO"};
        String[] jekItem = {"Laki - Laki", "Perempuan"};
        switch(cbKategori.getSelectedItem().toString()){
            case "Kelas":
                
                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                for(String itemKel : kelItem){
                    isiCb.addItem(itemKel);
                }
                flag = "kelas";
                break;
            case "Jurusan":
                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                for(String itemJur : jurItem){
                    isiCb.addItem(itemJur);
                }
                flag = "jurusan";
                break;
            case "Jenis Kelamin":
                isiCb.setEnabled(true);
                proceedBtn.setEnabled(true);
                isiCb.removeAllItems();
                for(String itemJek : jekItem){
                    isiCb.addItem(itemJek);
                }
                flag = "jekel";
                break;
            default:
                JOptionPane.showInputDialog(this, "Input salah");
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        
        showTbPeminjam("select * from peminjam where "+flag+" = '"+isiCb.getSelectedItem()+"'");
        isiCb.setEnabled(false);
        proceedBtn.setEnabled(false);
        flag = "";
        isiCb.removeAllItems();
        
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void tabelPeminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamMouseClicked
        // TODO add your handling code here:
        try{
            Statement st = MySqlCon.getConnection().createStatement();
            int baris = tabelPeminjam.getSelectedRow();
            String klik_tabel = (tabelPeminjam.getModel().getValueAt(baris, 0).toString());
            String query = "select * from peminjam where no_induk = '"+klik_tabel+"'";
            String induk="", nama="", jurusan="", kelas="", jekel="", alamat="", telp="";
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                induk = rs.getString("no_induk");
                nama = rs.getString("nama_siswa");
                jurusan = rs.getString("jurusan");
                kelas = rs.getString("kelas");
                jekel = rs.getString("jekel");
                alamat = rs.getString("alamat");
                telp = rs.getString("no_telp");
                lbl_noInduk.setText(induk);
                tfNama.setText(nama);
                jurusanCb.setSelectedItem(jurusan);
                kelasCb.setSelectedItem(kelas);
                jekelCb.setSelectedItem(jekel);
                alamatTa.setText(alamat);
                tfTelp.setText(telp);
                updateBtn.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Query salah");
        }
    }//GEN-LAST:event_tabelPeminjamMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            // TODO add your handling code here:
            String query = "update peminjam set nama_siswa='"+tfNama.getText()+"',jurusan ='"+jurusanCb.getSelectedItem()+"', kelas='"+kelasCb.getSelectedItem()+"', jekel='"+jekelCb.getSelectedItem()+"',alamat='"+alamatTa.getText()+"',no_telp='"+tfTelp.getText()+"' where no_induk='"+lbl_noInduk.getText()+"'";
            PreparedStatement ps = MySqlCon.getConnection().prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            showTbPeminjam("select * from peminjam");
            ps.close();
            lbl_noInduk.setText("");
            tfNama.setText("");
            alamatTa.setText("");
            tfTelp.setText("");
            updateBtn.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Query salah \nError : "+ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void showTbPeminjam(String query){
        try{
            Statement st = MySqlCon.getConnection().createStatement();
            try{
                Object[] rows = {"No induk", "Nama siswa", "Jurusan", "Kelas", "Jekel", "Alamat", "Telp"};
                DefaultTableModel  dtm=new DefaultTableModel(null,rows);
                tabelPeminjam.setModel(dtm);
                tabelPeminjam.setBorder(null);
                jScrollPane1.setVisible(true);
                jScrollPane1.setViewportView(tabelPeminjam);
                String induk="", nama="", jurusan="", kelas="", jekel="", alamat="", telp="";
                try{
                    
                    ResultSet rs = st.executeQuery(query);
                    while(rs.next()){
                        induk = rs.getString("no_induk");
                        nama = rs.getString("nama_siswa");
                        jurusan = rs.getString("jurusan");
                        kelas = rs.getString("kelas");
                        jekel = rs.getString("jekel");
                        alamat = rs.getString("alamat");
                        telp = rs.getString("no_telp");
                        
                        String[] row = {""+induk, nama, jurusan, kelas, jekel, alamat, telp};
                        dtm.addRow(row);
                    }
                    
                }
                catch(SQLException en){                
                    JOptionPane.showMessageDialog(null,"Query Salah "+en);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Query Salah "+e);
            }
        }catch(Exception ex){
            Logger.getLogger(kelolaPeminjam.class.getName()).log(Level.SEVERE,null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SortPane;
    private javax.swing.JTextArea alamatTa;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton indukBtn;
    private javax.swing.JComboBox<String> isiCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jekelCb;
    private javax.swing.JButton jurusanBtn;
    private javax.swing.JComboBox<String> jurusanCb;
    private javax.swing.JButton kelasBtn;
    private javax.swing.JComboBox<String> kelasCb;
    private javax.swing.JLabel lbl_noInduk;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JTable tabelPeminjam;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTelp;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updateDataPanel;
    // End of variables declaration//GEN-END:variables
}
